World = ['Japan', 'America', 'Philipines', 'Australia', 'New Zealand']
print(World)
print(sorted(World))
print(World)
World.reverse()
print(World)
World.reverse()
print(World)
World.sort()
print(World)
World.sort(reverse=True)
print(World)